const API_ENDPOINT = "https://discord.com/api/v6";
const MAX_EMBED_FIELD_CHARS = 1024;
const MAX_EMBED_FOOTER_CHARS = 2048;

module.exports = { API_ENDPOINT, MAX_EMBED_FIELD_CHARS, MAX_EMBED_FOOTER_CHARS };